apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: mypythonengine
          image: myworker   # create image that k8s (minikube) has access to
          imagePullPolicy: Never
          ports:
            - containerPort: 5000     # Flask
          command: ["/bin/sh", "-c", "python3 app.py"]  # running the worker

---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    app: worker
  type: ClusterIP                  # internal only (default)
  ports:
    - port: 8080                   # service port
      targetPort: 5000             # containerPort
